theme: minima
title: BatteryWise
description: A sustainable project in Engineering & Sustainability
navbar:
  - name: Introduction
    link: index.md
  - name: Materials
    link: materials.md
  - name: Electronics
    link: electronics.md
  - name: Software
    link: software.md
