theme: minima
title: BatteryWise
description: A sustainable project in Engineering & Sustainability
header_pages:
  - index.md
  - requirements.md
  - electronics.md
  - software.md
  - work-in-progress.md
