theme: minima
title: Battery**<span style="color:green;">Wise</span>**

description: A sustainable project in Engineering & Sustainability
header_pages:
  - index.md
  - materials.md
  - electronics.md
  - software.md
favicon: /images/favicon.ico
logo: /images/logo.png
footer_text: "© 2025 BatteryWise - Een duurzaam project voor batterijbeheer"

